spring:
  application:
    name: eiaun
  main:
    web-application-type: none

eiaun:
  control:
    duration_secs: -1
    processor_fraction: 0.9
    snapshots:
      enabled: true
      compression: zstd
      dump_interval: 100
  jakku:
    grid: 1000
    organisms:
      density: 0.4
      # type: io.eiaun.shared.organisms.simple.SimpleOrganism
      type: io.eiaun.shared.organisms.mover.Mover
      properties:
        "[io.eiaun.shared.organisms.simple.SimpleOrganism]":
          vision_radius: 5
        "[io.eiaun.shared.organisms.mover.Mover]":
          vision_radius: 3
          desirable_properties: 2
          peak_energy: 5
          move_energy: 1
          rest_energy: 0.5
    substances:
      density: 0.2
      specs:
      - abundance: 8.0
        id: Berkelium
        properties:
          Vapor: VFYLq
          OxidizingAgent: VExVN
          Reactivity: VXePs
          ColdFilterPluggingPoint: VHSbm
          AbsoluteMolarMass: VKpTB
          ElectricCharge: VoGSX
          TrueVaporPressure: V3Dit
          Anhydrous: VHUlg
          Adhesion: VKbA4
          Metastability: VBoAM
      - abundance: 14.0
        id: Arsenic
        properties:
          Vapor: VdXgM
          OxidizingAgent: VExVN
          Reactivity: VctHb
          ColdFilterPluggingPoint: VDiwE
          AbsoluteMolarMass: VGDKP
          ElectricCharge: VmxVl
          TrueVaporPressure: VlNxx
          Anhydrous: VxMI0
          Adhesion: VqHLK
          Metastability: VBoAM
      - abundance: 2.0
        child: Europium
        id: Aluminum
        properties:
          Vapor: VqIJw
          OxidizingAgent: VExVN
          Reactivity: Vb8nh
          ColdFilterPluggingPoint: VHSbm
          AbsoluteMolarMass: VKpTB
          ElectricCharge: VoGSX
          TrueVaporPressure: VlNxx
          Anhydrous: VxMI0
          Adhesion: VqHLK
          Metastability: V2JkN
      - abundance: 10.0
        id: Hydrogen
        properties:
          Vapor: VdXgM
          OxidizingAgent: VTyya
          Reactivity: VXePs
          ColdFilterPluggingPoint: VDiwE
          AbsoluteMolarMass: VKpTB
          ElectricCharge: VmxVl
          TrueVaporPressure: V3Dit
          Anhydrous: VMBIR
          Adhesion: VKbA4
          Metastability: V2JkN
      - abundance: 3.0
        id: Technetium
        properties:
          Vapor: VFYLq
          OxidizingAgent: VFk1W
          Reactivity: Vb8nh
          ColdFilterPluggingPoint: VdU4p
          AbsoluteMolarMass: VKpTB
          ElectricCharge: VmxVl
          TrueVaporPressure: V3Dit
          Anhydrous: VxMI0
          Adhesion: VqHLK
          Metastability: VKkkR
      - abundance: 2.0
        child: Berkelium
        id: Protactinium
        properties:
          Vapor: VdXgM
          OxidizingAgent: VTyya
          Reactivity: VctHb
          ColdFilterPluggingPoint: VHSbm
          AbsoluteMolarMass: VKpTB
          ElectricCharge: VNkpj
          TrueVaporPressure: VlNxx
          Anhydrous: VMBIR
          Adhesion: VqHLK
          Metastability: VKkkR
      - abundance: 3.0
        child: Rhodium
        id: Neon
        properties:
          Vapor: VFYLq
          OxidizingAgent: VExVN
          Reactivity: VctHb
          ColdFilterPluggingPoint: VdU4p
          AbsoluteMolarMass: VKpTB
          ElectricCharge: VoGSX
          TrueVaporPressure: V3Dit
          Anhydrous: VxMI0
          Adhesion: VKbA4
          Metastability: VBoAM
      - abundance: 6.0
        id: Platinum
        properties:
          Vapor: VqIJw
          OxidizingAgent: VExVN
          Reactivity: VctHb
          ColdFilterPluggingPoint: VHSbm
          AbsoluteMolarMass: Vizh7
          ElectricCharge: VoGSX
          TrueVaporPressure: VlNxx
          Anhydrous: VxMI0
          Adhesion: VKbA4
          Metastability: VBoAM
      - abundance: 2.0
        child: Curium
        id: Hafnium
        properties:
          Vapor: VdXgM
          OxidizingAgent: VExVN
          Reactivity: VctHb
          ColdFilterPluggingPoint: VHSbm
          AbsoluteMolarMass: Vizh7
          ElectricCharge: VoGSX
          TrueVaporPressure: VlNxx
          Anhydrous: VHUlg
          Adhesion: VKbA4
          Metastability: VKkkR
      - abundance: 4.0
        id: Titanium
        properties:
          Vapor: VqIJw
          OxidizingAgent: VTyya
          Reactivity: Vb8nh
          ColdFilterPluggingPoint: VHSbm
          AbsoluteMolarMass: VGDKP
          ElectricCharge: VNkpj
          TrueVaporPressure: VlNxx
          Anhydrous: VxMI0
          Adhesion: VKqlV
          Metastability: VKkkR
      - abundance: 2.0
        id: Americium
        properties:
          Vapor: VFYLq
          OxidizingAgent: VTyya
          Reactivity: VXePs
          ColdFilterPluggingPoint: VHSbm
          AbsoluteMolarMass: VKpTB
          ElectricCharge: VoGSX
          TrueVaporPressure: VHkuX
          Anhydrous: VMBIR
          Adhesion: VKqlV
          Metastability: V2JkN
      - abundance: 7.0
        child: Americium
        id: Silicon
        properties:
          Vapor: VdXgM
          OxidizingAgent: VFk1W
          Reactivity: VctHb
          ColdFilterPluggingPoint: VdU4p
          AbsoluteMolarMass: Vizh7
          ElectricCharge: VoGSX
          TrueVaporPressure: VHkuX
          Anhydrous: VMBIR
          Adhesion: VKbA4
          Metastability: VBoAM
      - abundance: 3.0
        id: Curium
        properties:
          Vapor: VFYLq
          OxidizingAgent: VTyya
          Reactivity: VctHb
          ColdFilterPluggingPoint: VDiwE
          AbsoluteMolarMass: VGDKP
          ElectricCharge: VmxVl
          TrueVaporPressure: VHkuX
          Anhydrous: VHUlg
          Adhesion: VqHLK
          Metastability: V2JkN
      - abundance: 3.0
        child: Nitrogen
        id: Lanthanum
        properties:
          Vapor: VdXgM
          OxidizingAgent: VTyya
          Reactivity: Vb8nh
          ColdFilterPluggingPoint: VdU4p
          AbsoluteMolarMass: VKpTB
          ElectricCharge: VNkpj
          TrueVaporPressure: VlNxx
          Anhydrous: VHUlg
          Adhesion: VqHLK
          Metastability: V2JkN
      - abundance: 27.0
        child: Hassium
        id: Europium
        properties:
          Vapor: VqIJw
          OxidizingAgent: VTyya
          Reactivity: VXePs
          ColdFilterPluggingPoint: VDiwE
          AbsoluteMolarMass: Vizh7
          ElectricCharge: VoGSX
          TrueVaporPressure: V3Dit
          Anhydrous: VHUlg
          Adhesion: VqHLK
          Metastability: VBoAM
      - abundance: 7.0
        child: Flerovium
        id: Bohrium
        properties:
          Vapor: VFYLq
          OxidizingAgent: VTyya
          Reactivity: Vb8nh
          ColdFilterPluggingPoint: VDiwE
          AbsoluteMolarMass: Vizh7
          ElectricCharge: VmxVl
          TrueVaporPressure: V3Dit
          Anhydrous: VxMI0
          Adhesion: VKqlV
          Metastability: V2JkN
      - abundance: 3.0
        child: Arsenic
        id: Praseodymium
        properties:
          Vapor: VqIJw
          OxidizingAgent: VExVN
          Reactivity: Vb8nh
          ColdFilterPluggingPoint: VdU4p
          AbsoluteMolarMass: Vizh7
          ElectricCharge: VmxVl
          TrueVaporPressure: V3Dit
          Anhydrous: VxMI0
          Adhesion: VKqlV
          Metastability: VKkkR
      - abundance: 23.0
        child: Manganese
        id: Bromine
        properties:
          Vapor: VdXgM
          OxidizingAgent: VExVN
          Reactivity: Vb8nh
          ColdFilterPluggingPoint: VHSbm
          AbsoluteMolarMass: Vizh7
          ElectricCharge: VNkpj
          TrueVaporPressure: V3Dit
          Anhydrous: VxMI0
          Adhesion: VKbA4
          Metastability: VKkkR
      - abundance: 4.0
        child: Americium
        id: Flerovium
        properties:
          Vapor: VFYLq
          OxidizingAgent: VTyya
          Reactivity: VctHb
          ColdFilterPluggingPoint: VHSbm
          AbsoluteMolarMass: VKpTB
          ElectricCharge: VoGSX
          TrueVaporPressure: V3Dit
          Anhydrous: VHUlg
          Adhesion: VqHLK
          Metastability: V2JkN
      - abundance: 17.0
        child: Potassium
        id: Oxygen
        properties:
          Vapor: VFYLq
          OxidizingAgent: VTyya
          Reactivity: Vb8nh
          ColdFilterPluggingPoint: VdU4p
          AbsoluteMolarMass: VKpTB
          ElectricCharge: VoGSX
          TrueVaporPressure: VHkuX
          Anhydrous: VHUlg
          Adhesion: VKbA4
          Metastability: VKkkR
      - abundance: 7.0
        child: Praseodymium
        id: Tennessine
        properties:
          Vapor: VFYLq
          OxidizingAgent: VTyya
          Reactivity: Vb8nh
          ColdFilterPluggingPoint: VHSbm
          AbsoluteMolarMass: VGDKP
          ElectricCharge: VmxVl
          TrueVaporPressure: V3Dit
          Anhydrous: VMBIR
          Adhesion: VKqlV
          Metastability: V2JkN
      - abundance: 3.0
        child: Zirconium
        id: Dysprosium
        properties:
          Vapor: VdXgM
          OxidizingAgent: VFk1W
          Reactivity: Vb8nh
          ColdFilterPluggingPoint: VDiwE
          AbsoluteMolarMass: VKpTB
          ElectricCharge: VoGSX
          TrueVaporPressure: VHkuX
          Anhydrous: VHUlg
          Adhesion: VqHLK
          Metastability: VBoAM
      - abundance: 9.0
        id: Nitrogen
        properties:
          Vapor: VFYLq
          OxidizingAgent: VExVN
          Reactivity: Vb8nh
          ColdFilterPluggingPoint: VHSbm
          AbsoluteMolarMass: Vizh7
          ElectricCharge: VmxVl
          TrueVaporPressure: VHkuX
          Anhydrous: VHUlg
          Adhesion: VKbA4
          Metastability: V2JkN
      - abundance: 3.0
        child: Potassium
        id: Lutetium
        properties:
          Vapor: VFYLq
          OxidizingAgent: VFk1W
          Reactivity: Vb8nh
          ColdFilterPluggingPoint: VdU4p
          AbsoluteMolarMass: Vizh7
          ElectricCharge: VmxVl
          TrueVaporPressure: VHkuX
          Anhydrous: VHUlg
          Adhesion: VqHLK
          Metastability: VBoAM
      - abundance: 4.0
        child: Hafnium
        id: Zirconium
        properties:
          Vapor: VFYLq
          OxidizingAgent: VFk1W
          Reactivity: VctHb
          ColdFilterPluggingPoint: VdU4p
          AbsoluteMolarMass: VGDKP
          ElectricCharge: VNkpj
          TrueVaporPressure: V3Dit
          Anhydrous: VHUlg
          Adhesion: VqHLK
          Metastability: V2JkN
      - abundance: 4.0
        id: Rhodium
        properties:
          Vapor: VFYLq
          OxidizingAgent: VTyya
          Reactivity: VXePs
          ColdFilterPluggingPoint: VHSbm
          AbsoluteMolarMass: Vizh7
          ElectricCharge: VoGSX
          TrueVaporPressure: VHkuX
          Anhydrous: VMBIR
          Adhesion: VKqlV
          Metastability: V2JkN
      - abundance: 13.0
        child: Flerovium
        id: Hassium
        properties:
          Vapor: VFYLq
          OxidizingAgent: VTyya
          Reactivity: VXePs
          ColdFilterPluggingPoint: VHSbm
          AbsoluteMolarMass: Vizh7
          ElectricCharge: VoGSX
          TrueVaporPressure: V3Dit
          Anhydrous: VMBIR
          Adhesion: VKqlV
          Metastability: VBoAM
      - abundance: 12.0
        id: Einsteinium
        properties:
          Vapor: VFYLq
          OxidizingAgent: VExVN
          Reactivity: VctHb
          ColdFilterPluggingPoint: VDiwE
          AbsoluteMolarMass: VGDKP
          ElectricCharge: VNkpj
          TrueVaporPressure: VHkuX
          Anhydrous: VxMI0
          Adhesion: VqHLK
          Metastability: V2JkN
      - abundance: 3.0
        child: Hydrogen
        id: Potassium
        properties:
          Vapor: VqIJw
          OxidizingAgent: VExVN
          Reactivity: VctHb
          ColdFilterPluggingPoint: VDiwE
          AbsoluteMolarMass: VGDKP
          ElectricCharge: VoGSX
          TrueVaporPressure: VHkuX
          Anhydrous: VMBIR
          Adhesion: VqHLK
          Metastability: VKkkR
      - abundance: 13.0
        child: Lutetium
        id: Manganese
        properties:
          Vapor: VFYLq
          OxidizingAgent: VExVN
          Reactivity: VctHb
          ColdFilterPluggingPoint: VHSbm
          AbsoluteMolarMass: VKpTB
          ElectricCharge: VoGSX
          TrueVaporPressure: VlNxx
          Anhydrous: VMBIR
          Adhesion: VKbA4
          Metastability: V2JkN